### PR TITLE
Ss3 compatibility

### PR DESCRIPTION
**Pull request by svandragt**
Hi Hamish,
Please find enclosed an pull request containing initial ss3 compatibility fixes, and more flexible group matching code.

Currently developing a SilverStripe intranet solution that is using this in a Windows Active Directory setting, so will continue updating this where required.

### CODE REVIEW

**Comment by Weishaupt** [comment]
Hey @svandragt you should add your changes to the CHANGELOG as well. Thank you for the work. I will try out if the branch works for me.

**Comment by svandragt** [comment]
Yeah no problem will do so in the next few days, and add (if) any further bugfixes.

**Comment by svandragt** [comment]
It seems there is a problem with my repo or GitHub for Windows, when using my repo http://i.imm.io/JEC2.png. I'm waiting for response from GitHub on an email I sent them. Until then I cannot use this repo and therefore not move this on.

**Comment by hamishcampbell** [comment]
Hey thanks,

I've tagged the current release as ss-2.x so people can find the relevant commit for backwards compat.

Could you just fix up the whitespace in `code/ExternalAuthenticator.php` (`groupObj` method is strangely aligned) and update CHANGELOG, and I'll merge.

Thanks!

**Comment by hamishcampbell** [comment]
Also, method comments =D

**Comment by nathanbrauer** [comment]
Updates?

**Comment by svandragt** [comment]
I just updated GitHub for Windows the 1.0.32 release fixes the problems reported earlier, therefore I can now use this repository once more. I will now start looking at the comments on this pull request and will update this pull request once this is done.

**Comment by nathanbrauer** [comment]
Awesome! Looking forward to it!

**Comment by svandragt** [comment]
Please find enclosed the fixes as requested. I'm using this code in production for our institution's SilverStripe websites. Sorry for the spelling mistake on the log message  'indendation fix'.

**Comment by hamishcampbell** [comment]
Awesome, thanks!!

**Comment by hamishcampbell** [comment]
PS added @svandragt as collaborator so you can push any fixes, etc :smile:

**Comment by svandragt** [comment]
Thanks Hamish (love that name btw)

**Pull request merged**
